### ISSUE TITLE
Remove Image Folder.

### ISSUE THREAD

**Issue by DeltaCoderr** [Spiderjockey02/Discord-Bot#1]
While I was checking out the commands, I saw that your repo has two Image folders one is named `Image` and the other one is named as `image` both contain the same commands, So kindly remove one of the folders so It shouldn't affect anything.

Edit : There are two nsfw folders as well.

**Comment by Spiderjockey02** [comment]
Sorry, thank you for notifing me. I was meant to delete `image` folder.

**Comment by DeltaCoderr** [comment]
aight no worries

**Comment by Spiderjockey02** [comment]
Files have been corrected.
