### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by puppala-koushik** [Spiderjockey02/Discord-Bot#106]
How to activate auto mode in your bot

**Comment by Spiderjockey02** [comment]
auto mode?

**Comment by puppala-koushik** [comment]
yes

**Comment by puppala-koushik** [comment]
auto mod

**Comment by Spiderjockey02** [comment]
oh, it hasn't fully been implemented. but the code can be found here to work out what settings needs to be enabled https://github.com/Spiderjockey02/Discord-Bot/blob/master/src/helpers/auto-moderation.js

**Comment by puppala-koushik** [comment]
ok still not completed dashboard also i think

**Comment by Spiderjockey02** [comment]
yh, im working on some optimization for the bot and then a few more things and then i'll finish the website.
