### ISSUE TITLE
shard error

### ISSUE THREAD

**Issue by HellpMe** [Spiderjockey02/Discord-Bot#108]
I'm having these errors when starting the bot

 Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
 
 Request failed with status code 400

**Comment by Spiderjockey02** [comment]
Can i see the whole error message? maybe a screenshot if possible

**Comment by HellpMe** [comment]
![send2](https://user-images.githubusercontent.com/64676117/109197773-2d9f5980-777c-11eb-8bbf-cd366976ecbc.png)
![send](https://user-images.githubusercontent.com/64676117/109197775-2e37f000-777c-11eb-88c8-5279a0b50901.png)

**Comment by Spiderjockey02** [comment]
you should of read the error in red as that tells you that u need to enable the priviledged intents at https://discordapp.com/developers/applications

**Comment by HellpMe** [comment]
It worked, thank you !!, do you want me to help you translate to pt-BR? it's my native language, if you want I can translate for you

**Comment by Spiderjockey02** [comment]
oh damn that would be amazing, thank you

**Comment by HellpMe** [comment]
I will call you on the discord
