### ISSUE TITLE
Hi I want to contribute in your project.

### ISSUE THREAD

**Issue by puppala-koushik** [Spiderjockey02/Discord-Bot#113]
Hey I have an idea like user prefix so that the user prefix is only prefix which can be used by user in any server. But I have one doubt that I was unable to find command handler

**Comment by puppala-koushik** [comment]
and can I add languages also

**Comment by Spiderjockey02** [comment]
per-user prefixes for the bot is unneccessary and takes up too much storage/processing power, if you want implement it yourself.
You can add any language you want, just send me the files on discord and i'll upload them to the repo.

**Comment by puppala-koushik** [comment]
Where is commands handler

**Comment by puppala-koushik** [comment]
hey where is this file helpers/DiscordBotListUpdate

**Comment by puppala-koushik** [comment]
in ready.js line 16
