### ISSUE TITLE
Strange Error (Using Repl.it)

### ISSUE THREAD

**Issue by Jonfirexbox** [Spiderjockey02/Discord-Bot#118]
i keep getting this error: 
[21:55:20]: LOG =-=-=-=-=-=-=- Loading command(s): 125 -=-=-=-=-=-=-= 
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:84) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Discord-Bot/src/bot.js:14:34
    at Array.forEach (<anonymous>)
    at /home/runner/Discord-Bot/src/bot.js:13:13
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[21:55:20]: LOG =-=-=-=-=-=-=- Loading events(s): 27 -=-=-=-=-=-=-= 
[21:55:20]: LOG Loading Event: debug 
[21:55:20]: LOG Loading Event: emojiCreate 
[21:55:20]: LOG Loading Event: emojiDelete 
[21:55:20]: LOG Loading Event: emojiUpdate 
[21:55:20]: LOG Loading Event: error 
[21:55:20]: LOG Loading Event: guildBanAdd 
[21:55:20]: LOG Loading Event: guildBanRemove 
[21:55:20]: LOG Loading Event: guildDelete 
[21:55:20]: LOG Loading Event: guildMemberAdd 
[21:55:20]: LOG Loading Event: guildMemberRemove 
[21:55:20]: LOG Loading Event: guildMemberUpdate 
[21:55:20]: LOG Loading Event: guildUnavailable 
[21:55:20]: LOG Loading Event: guildUpdate 
[21:55:20]: LOG Loading Event: message 
[21:55:20]: LOG Loading Event: messageDelete 
[21:55:20]: LOG Loading Event: messageDeleteBulk 
[21:55:20]: LOG Loading Event: messageReactionAdd 
[21:55:20]: LOG Loading Event: messageReactionRemove 
[21:55:20]: LOG Loading Event: messageUpdate 
[21:55:20]: LOG Loading Event: ready 
[21:55:20]: LOG Loading Event: roleCreate 
[21:55:20]: LOG Loading Event: roleDelete 
[21:55:20]: LOG Loading Event: roleUpdate 
[21:55:20]: LOG Loading Event: shardDisconnect 
[21:55:20]: LOG Loading Event: shardError 
[21:55:20]: LOG Loading Event: voiceStateUpdate 
[21:55:20]: LOG Loading Event: warn 
CloseEvent {
  target: WebSocket {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 4014,
    _closeFrameReceived: true,
    _closeFrameSent: true,
    _closeMessage: 'Disallowed intent(s).',
    _closeTimer: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 1320,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 165,
      [Symbol(triggerId)]: 105
    },
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: Receiver {
      _writableState: [WritableState],
      writable: false,
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _extensions: {},
      _isServer: false,
      _maxPayload: 104857600,
      _bufferedBytes: 0,
      _buffers: [],
      _compressed: false,
      _payloadLength: 23,
      _mask: undefined,
      _fragmented: 0,
      _masked: false,
      _fin: true,
      _opcode: 8,
      _totalPayloadLength: 0,
      _messageLength: 0,
      _fragments: [],
      _state: 0,
      _loop: false,
      [Symbol(kCapture)]: false,
      [Symbol(websocket)]: [Circular]
    },
    _sender: Sender {
      _extensions: {},
      _socket: [TLSSocket],
      _firstFragment: true,
      _compress: false,
      _bufferedBytes: 0,
      _deflating: false,
      _queue: []
    },
    _socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'gateway.discord.gg',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 5,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'gateway.discord.gg',
      _readableState: [ReadableState],
      readable: false,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 105,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 1085,
      [Symbol(kBytesWritten)]: 589,
      [Symbol(connect-options)]: [Object],
      [Symbol(websocket)]: undefined
    },
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://gateway.discord.gg/?v=6&encoding=json',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'close',
  wasClean: true,
  reason: 'Disallowed intent(s).',
  code: 4014
}
0
[21:55:20]: ERROR Privileged intent provided is not enabled or whitelisted. 
[21:55:20]: READY Mongoose connection successfully opened
(im also using repl.it to host the bot)

**Comment by Spiderjockey02** [comment]
please update your config file and enable privileged intents. 
Before making an issue, make sure you have the most up to date files and read the FAQ.

**Comment by Jonfirexbox** [comment]
ok
