### ISSUE TITLE
How to use the bot?

### ISSUE THREAD

**Issue by alext30Developer** [Spiderjockey02/Discord-Bot#125]
What is the prefix that you have to use in order for the bot to work?

**Comment by SirHoDo** [comment]
> What is the prefix that you have to use in order for the bot to work?

Provided you've setup the bot correctly, the default prefix is "e!" 

This can be changed inside your database or with eval commands!

**Comment by alext30Developer** [comment]
I have found this in the configuration file but I am unable to make my bot function correctly for some reason.

**Comment by SirHoDo** [comment]
> I have found this in the configuration file but I am unable to make my bot function correctly for some reason. 

Please join the support server (https://discord.com/invite/8g6zUQu)

Use the support channels for some easier help :)

**Comment by Spiderjockey02** [comment]
Issues has been closed as this is not an issue with the bot but rather something the user must research into.
