### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DynamoYT** [Spiderjockey02/Discord-Bot#126]
Queue should show previous songs also as like groovy bot.

**Comment by Spiderjockey02** [comment]
This will be looked at once the playlist support has been fully implemented

**Comment by Spiderjockey02** [comment]
This feature was added about 2 weeks (sorry forgot to mention this to anyone else who was paying attention to this issue) but a few more tweaks need to be added for me to be fully happy with it.

**Comment by omxpro** [comment]
Thanks!

**Comment by ChaosArising** [comment]
[Accidently Re-Opened]
