### ISSUE TITLE
Error when trying to user Music commands

### ISSUE THREAD

**Issue by Helixable** [Spiderjockey02/Discord-Bot#134]
When I use the `join` command, I get this error:
![image](https://user-images.githubusercontent.com/40667360/113351034-4913fc00-9308-11eb-956d-7aee88218891.png)
![image](https://user-images.githubusercontent.com/40667360/113351063-5204cd80-9308-11eb-8dfe-ea0b5b16f0bc.png)

Any idea what this means?

**Comment by Spiderjockey02** [comment]
well you have no nodes, you need to connect to a lavalink server

**Comment by Spiderjockey02** [comment]
User issue closed due to inactivity.
