### ISSUE TITLE
I need help hosting the bot on replit pls talk to me in discord rubi#1111 ( my nitro ends tomorrow)

### ISSUE THREAD

**Issue by rubi72** [Spiderjockey02/Discord-Bot#135]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. iOS, Window]
 - Browser [e.g. chrome, safari] ?

**Additional context**

**Comment by SirHoDo** [comment]
I've sent you a request on discord( Ethan Primmer#1089

**Comment by Spiderjockey02** [comment]
Ethan is not the owner nor a contributer to this repo, they are just a normal user. Just send a message to the support seever

**Comment by rubi72** [comment]
send the support server pls

**Comment by rubi72** [comment]
> I've sent you a request on discord( Ethan Primmer#1089

Oh, i decline sorry, i send u again

**Comment by Spiderjockey02** [comment]
> send the support server pls

the link is on the main page

**Comment by rubi72** [comment]
> > send the support server pls
> 
> the link is on the main page

I join, help
