### ISSUE TITLE
Dose This Work on Relp? Dm me On Discord (CustomKing#0001)

### ISSUE THREAD

**Issue by CustomDylan** [Spiderjockey02/Discord-Bot#136]
I need Help getting This Started in repl and hosting it, my discord username and tag is (CustomKing#0001) Dm me!

**Comment by Spiderjockey02** [comment]
I believe it does work on repl.it but you would need to find separate hosting for the lavalink ser er

**Comment by CustomDylan** [comment]
> I believe it does work on repl.it but you would need to find separate hosting for the lavalink server

Can you help me set it up and everything?

**Comment by rubi72** [comment]
> r

Same

**Comment by Spiderjockey02** [comment]
> Can you help me set it up and everything?

No, that's why I have the installation guide just follow that if you need more help just ask in the support server

**Comment by CustomDylan** [comment]
> > Can you help me set it up and everything?
> 
> No, that's why I have the installation guide just follow that if you need more help just ask in the support server

ok
