### ISSUE TITLE
where is the prefix command

### ISSUE THREAD

**Issue by puppala-koushik** [Spiderjockey02/Discord-Bot#137]
Where is the prefix command in your bot means how to change prefix using command

**Comment by ChaosArising** [comment]
There is no actual prefix command, if you want to change the prefix you need to change the prefix value in the guild. There seems to be a method you can use, `message.guild.updateGuild()`. You can also manually update it using the MongoDB compass application.
If you want to change the default prefix for the future, navigate to the GuildSettings schema, using the dir: `src/database/models/GuildSettings.js` and change the value of `prefix: {}`.

You can get a better answer if you join the developers server: https://discord.gg/SY2V3d8Q
