### ISSUE TITLE
Adding new category commands or renameing category

### ISSUE THREAD

**Issue by puppala-koushik** [Spiderjockey02/Discord-Bot#140]
Hey I am adding my own Bot hosting commands and I made a new category and I have changed the category of host commands.
when I changed the name of a category or when I create a new category those commands are not working can you please help me...!

**Comment by SirHoDo** [comment]
> Hey I am adding my own Bot hosting commands and I made a new category and I have changed the category of host commands.
> 
> when I changed the name of a category or when I create a new category those commands are not working can you please help me...!

Make sure the new category name is updated ￼inside the Plugins array in the database.

**Comment by puppala-koushik** [comment]
Yes they are showing in help command also but not working

**Comment by tovade** [comment]
thats an issue on your end then because **YOU** made the code

**Comment by puppala-koushik** [comment]
But the command made in misc category they are working
