### ISSUE TITLE
Plss help

### ISSUE THREAD

**Issue by TeunHessels** [Spiderjockey02/Discord-Bot#194]
![image](https://user-images.githubusercontent.com/52382388/125087289-aae4be80-e0cc-11eb-9f92-6fdef7e053ae.png)

plss help

**Comment by ChaosArising** [comment]
This issue occurs when you are on the wrong node version. You are required to be on node v14 or higher for the bot to function. Please consider updating.

If you need more support please use our discord support server:
https://discord.gg/pdks4pGF
