### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by PratikJena-ops** [Spiderjockey02/Discord-Bot#203]
![image](https://user-images.githubusercontent.com/80625019/127106561-5a86d8f6-8c04-46ba-837d-5fb0181151a5.png)
see this please and help me resolve the issue

**Comment by Wolfkid200444** [comment]
What is your current Node Version?

**Comment by Spiderjockey02** [comment]
> What is your current Node Version?

This was responded in the support server just forgot to close this issue, but thanks anyways.
