### ISSUE TITLE
How to change the default prefix

### ISSUE THREAD

**Issue by TeunHessels-jpg** [Spiderjockey02/Discord-Bot#229]
How do I change the default prefix of the bot

**Comment by KimYou-Developer** [comment]
@TeunHessels-jpg  , I think over here ( `Discord-Bot/src/assets/json/defaultGuildSettings.json` )

**Comment by Spiderjockey02** [comment]
This issue has been resolved in the Discord server, but thanks anyways for helping. (Gonna close now)
