### ISSUE TITLE
Unhandle Promise Rejection

### ISSUE THREAD

**Issue by Woogiesii** [Spiderjockey02/Discord-Bot#230]
Always getting this when playing some music is it because the lavalink or anything else ?

![image](https://user-images.githubusercontent.com/70749185/132097207-31f9aeac-57a6-43a5-b6f0-70de16cf8ff1.png)

**Comment by Spiderjockey02** [comment]
This is due to mongo not actually updating all the guild settings, this will be fixed soon. (Shouldn't affect your code).
The bug appears when someone joins a server with a guild that has old server settings.

**Comment by Woogiesii** [comment]
Ahh okay thanks for the information.

**Comment by Spiderjockey02** [comment]
Just a quick one how many servers is your bot in? Seeing if there's a cap or something

**Comment by Woogiesii** [comment]
> Just a quick one how many servers is your bot in? Seeing if there's a cap or something

it's just 4 servers

**Comment by Spiderjockey02** [comment]
oh then you might just be able to do `e!scripts update-database-v1.2`. (just change the prefix to yours)

**Comment by Woogiesii** [comment]
> oh then you might just be able to do `e!scripts update-database-v1.2`. (just change the prefix to yours)

ahh okay thankss

**Comment by Woogiesii** [comment]
![image](https://user-images.githubusercontent.com/70749185/132130936-c9c11259-b65f-4047-bc05-fdd4849383bc.png)
is this problem from my vps or lavalink ?

**Comment by Woogiesii** [comment]
and new error when i play some music after 3 minutes after queue is clear the bot will give no voice and need to rejoin again

**Comment by Spiderjockey02** [comment]
> ![image](https://user-images.githubusercontent.com/70749185/132130936-c9c11259-b65f-4047-bc05-fdd4849383bc.png)
> is this problem from my vps or lavalink ?

It could be both as it took too long to get a response from the lavalink server, so double check each server for any bottlenecks.

**Comment by Spiderjockey02** [comment]
> and new error when i play some music after 3 minutes after queue is clear the bot will give no voice and need to rejoin again

After 3 mins of empty queue, the bot will leave the VC this is intended.
