### ISSUE TITLE
plss help 

### ISSUE THREAD

**Issue by TeunHessels** [Spiderjockey02/Discord-Bot#231]
![image](https://user-images.githubusercontent.com/52382388/132131031-9c4fe26d-cf63-400e-b141-bd3482415798.png)
goldencredit gave me help but that doesnt work no i know i get this error

**Comment by Woogiesii** [comment]
wait i think there's no code like that in the latest version of the bot

**Comment by Spiderjockey02** [comment]
Gonna close this issue as it's being resolved on the discord server.
