### ISSUE TITLE
[BUG] Rank command

### ISSUE THREAD

**Issue by yawn999** [Spiderjockey02/Discord-Bot#253]
**Describe the bug**
When running rank command, nothing shows
 
**To Reproduce**
1. Go to a server the bot is on
2. Run command rank

**Expected behavior**
Seeing what rank (or someones level) you are in channel.

**Screenshots**
I dont think screenshots are needed since if anyone simply runs the command, nothing shows. 

**Device (please complete the following information):**
 - Windows 64x

**Comment by GoldenCredit101** [comment]
Rank command does work as intended.

**Comment by Spiderjockey02** [comment]
are you sure the command loaded correctly and that the level plugin is active (check via help command) ?

**Comment by yawn999** [comment]
weird. It works now. Thanks.
