### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by louisplayzz** [Spiderjockey02/Discord-Bot#297]
can you add a dashboard to it

**Comment by Spiderjockey02** [comment]
![image](https://user-images.githubusercontent.com/55885015/145436099-ca339843-2574-4e83-8242-8de409ea5bbd.png)


tl;dr: I'm not releasing a dashboard anytime soon as I believe the bot is far enough already good as an open-source bot and just releasing a dashboard aswell will make people not learn JavaScript and just flood discord bot list with a ton of copies

**Comment by louisplayzz** [comment]
oh okey
