### ISSUE TITLE
Cant use music features

### ISSUE THREAD

**Issue by TylerNe** [Spiderjockey02/Discord-Bot#310]
![image](https://user-images.githubusercontent.com/91006119/147564456-24fde7c8-6ab2-4c49-b795-05ed750e00c0.png)
It said no avable nodes when i use command play

**Comment by Spiderjockey02** [comment]
Yes, cuz you haven't connected to a lavalink server. Please read the installation guide

**Comment by TylerNe** [comment]
Hi, i dont how to have a lavaLink so can u help me with it pls
thanks
Tyler

**Comment by Spiderjockey02** [comment]
Join the support server: https://discord.gg/8g6zUQu for easier support
