### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by csj90** [Spiderjockey02/Discord-Bot#319]
the website is not loading for me for the bot

**Comment by Spiderjockey02** [comment]
What are you hosting the bot on?

**Comment by csj90** [comment]
my vps server

**Comment by Spiderjockey02** [comment]
it should be `ip:port` so for example `localhost:3000` (Just make sure port 3000 is forwarded so people outside the network, YOU, can connect to iy)

**Comment by csj90** [comment]
tried that and no dice

**Comment by Spiderjockey02** [comment]
First make sure port 3000 is running -> https://www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/

**Comment by csj90** [comment]
now i am getting this <html><body>


error | "Invalid API token"
-- | --



</body>
</html>

**Comment by csj90** [comment]
how would i find my api token ?

**Comment by Spiderjockey02** [comment]
ah nice, either in the config set API.secure to false or add `?token=YOUTOKEN` to the end of your URL (replace YOUTOKEN with API.token)

**Comment by csj90** [comment]
now when that port works but i cant view each servers dashboards

**Comment by Spiderjockey02** [comment]
It's not a dashboard but rather an API for you to make a dashboard
