### ISSUE TITLE
could you make all commands a interaction command

### ISSUE THREAD

**Issue by Louissplayz** [Spiderjockey02/Discord-Bot#349]
Could you make all commands a interactioncommand?

becouse i found that some of the commands not interaction command is

**Comment by Spiderjockey02** [comment]
we deliberately ignored some categories just for now to get the feature out and running to the public. They will be worked on later when seen fit, like when the dashboard is at a good level of completion so people can choose what commands are interactions etc.

going keep this issue open till all the commands are interactions

**Comment by louisplayz-inc** [comment]
okay thank you

**Comment by Spiderjockey02** [comment]
This is now been completed

**Comment by Louissplayz** [comment]
okey thx
