### ISSUE TITLE
DASHBOARD ERROR

### ISSUE THREAD

**Issue by koushikpuppala5** [Spiderjockey02/Discord-Bot#35]
I have getting an error about the dashboard login

![2020-11-17 (4)_LI](https://user-images.githubusercontent.com/70138027/99384693-cf014e80-28f5-11eb-8437-811b98b561ea.jpg)

**Comment by Spiderjockey02** [comment]
Go to line 41 and remove bot.config.botID to your bot ID (I will fix this soon)

**Comment by koushikpuppala5** [comment]
In which file

**Comment by Spiderjockey02** [comment]
Oh lol sorry forgot to tell you. Its in the dashboard.js file (src/modules/website)

**Comment by koushikpuppala5** [comment]
How many lines should I remove

**Comment by Spiderjockey02** [comment]
![image](https://user-images.githubusercontent.com/55885015/99386561-95671e00-28ca-11eb-87ab-7d7c9fb65a0b.png)
don't remove any, just replace bot.config.botID, with your Bot's ID. 
Found here vv
![image](https://user-images.githubusercontent.com/55885015/99386655-b465b000-28ca-11eb-8586-f739f44859ae.png)

**Comment by koushikpuppala5** [comment]
ok i will try

**Comment by koushikpuppala5** [comment]
my server is somewhat slow

**Comment by Spiderjockey02** [comment]
server? it could just be your host/specs.
Also the dashboard isn't finished so it may have some bugs

**Comment by koushikpuppala5** [comment]
which dashboard

**Comment by Spiderjockey02** [comment]
the dashboard in the bot (the website). The reason why you made this issue

**Comment by koushikpuppala5** [comment]
ok
