### ISSUE TITLE
Volume command dosen't show output but works.

### ISSUE THREAD

**Issue by LifeDreamer24** [Spiderjockey02/Discord-Bot#362]
**Describe the bug**
Volume command dosen't show output but works. (Unhandled promise rejection: Cannot send an empty message.)

**To Reproduce**
1. Adjust the volume using the command.
2. Wait infinitely for a reply.

**Expected behavior**
Show an embed reply?

**Screenshots**

**Device (please complete the following information):**
 - Windows
 - Latest Version

**Additional context**

**Comment by Spiderjockey02** [comment]
What was the full command and was it a slash command or prefix command? (e.g `e!volume 45`)

**Comment by LifeDreamer24** [comment]
Slash

**Comment by LifeDreamer24** [comment]
For example:
/volume 20

**Comment by LifeDreamer24** [comment]
Thanks for fixing 👍

**Comment by Spiderjockey02** [comment]
yep fixed and confirmed.
