### ISSUE TITLE
Giveaway function error

### ISSUE THREAD

**Issue by pengengantibaju** [Spiderjockey02/Discord-Bot#391]
I tried use g-start function not work

**Comment by jmundr** [comment]
You need to be more precise on your issue, saying 'not work' isn't helpful nor descriptive - provide screenshots of the logs. If you have Discord please consider joining our server for faster response times.

**Comment by ChaosArising** [comment]
You need to be more precise on your issue, saying 'not work' isn't helpful nor descriptive - provide screenshots of the logs. If you have Discord please consider joining our server for faster response times.

**Comment by Spiderjockey02** [comment]
All giveaway stuff should be working now
