### ISSUE TITLE
Some slash commands don't work but with message commands it does.

### ISSUE THREAD

**Issue by JJ-Universe** [Spiderjockey02/Discord-Bot#438]
![image](https://user-images.githubusercontent.com/46922562/187830118-c657bd85-f4fa-4053-956b-c1e690463a29.png)
![image](https://user-images.githubusercontent.com/46922562/187829665-b76b342a-917e-4103-8fdc-56780e0b7ed4.png)
Please fix this.

**Comment by Spiderjockey02** [comment]
This issue is already on my things to do. It will be fixed when I complete the rewrite for discord.js v14.

**Comment by JJ-Universe** [comment]
Okay.

**Comment by Spiderjockey02** [comment]
This should be fixed now
