### ISSUE TITLE
Channel.error is not a function

### ISSUE THREAD

**Issue by vSilva-gb** [Spiderjockey02/Discord-Bot#445]
**Describe the bug**
Whenever a command is used in a voice text channel and calls the channel.error or channel.success function it gives this error

**To Reproduce**
1. Go to 'Voice Text Channel'
2. Use a command that calls the channel.error function

**Screenshots**
https://media.discordapp.net/attachments/599404709433966607/1018668558017896448/unknown.png
https://media.discordapp.net/attachments/599404709433966607/1018668626271805560/unknown.png

**Device (please complete the following information):**
 - OS: [e.g. iOS, Window]
 - Browser [e.g. chrome, safari] ?

**Additional context**

**Comment by Spiderjockey02** [comment]
This should be fixed now in the latest [commit](https://github.com/Spiderjockey02/Discord-Bot/commit/54d878e0f111b9f4b7ef87063e1118e1e13c5162).
