### ISSUE TITLE
EgglordEmbed is apparently broken

### ISSUE THREAD

**Issue by vSilva-gb** [Spiderjockey02/Discord-Bot#448]
**Describe the bug**
If you use an Embed that uses the EgglordEmbed title it simply will not show the title, one case that happens is the Track Start embed message.

**To Reproduce**
1. Play a song and see the Track Start embed without the title

**Expected behavior**
The title message was expected in all embed embed that use egglordEmbed but it doesn't happen

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/3GbH7FLMvfmt)

**Device (please complete the following information):**
 - OS: [e.g. iOS, Window]
 - Browser [e.g. chrome, safari] ?

**Additional context**

**Comment by Spiderjockey02** [comment]
Should be fixed now, thank you for spotting it.
