### ISSUE TITLE
  Chalk 5 has changed to ESM.

### ISSUE THREAD

**Issue by JhoN-yo** [Spiderjockey02/Discord-Bot#490]
### From chalk README:

> IMPORTANT: Chalk 5 is ESM. If you want to use Chalk with TypeScript or a build tool, you will probably want to use Chalk 4 for now.

**-** They provide a link to better understand what that means: [Pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Comment by birongliu** [comment]
But the bot isn't written in typescript

**Comment by JhoN-yo** [comment]
> But the bot isn't written in typescript

But chalk triggers error when starting the bot, I had to return chalk to v4

**Comment by Spiderjockey02** [comment]
🤦I accidentally upgraded it when I was updating all the dependencies. 
It has now been fixed.
