### ISSUE TITLE
Lavalink

### ISSUE THREAD

**Issue by JustANormalProgramm3r** [Spiderjockey02/Discord-Bot#532]
Whenever I run the bot it gives me this error:
`Lavalink node: 'localhost', has error: 'connect ECONNREFUSED ::1:5000`

**Comment by Spiderjockey02** [comment]
Are you running the lavalink server on that port?

**Comment by JustANormalProgramm3r** [comment]
i'm running it

**Comment by JustANormalProgramm3r** [comment]
on that port

**Comment by birongliu** [comment]
Is your credentials same in yml file and config

**Comment by JustANormalProgramm3r** [comment]
yes

**Comment by Spiderjockey02** [comment]
Also just a quick on, ::1 is an IPv6 address, can you try just using localhost (or the IPv4 address of the server running the lavalink)?

**Comment by JustANormalProgramm3r** [comment]
i put localhost

**Comment by birongliu** [comment]
In your application.yml is your address: 0.0.0.0

**Comment by JustANormalProgramm3r** [comment]
no

**Comment by birongliu** [comment]
For hosting locally i recommend you not change the address property

**Comment by JustANormalProgramm3r** [comment]
okay i'll try switching it back to 0.0.0.0

**Comment by JustANormalProgramm3r** [comment]
`Lavalink node: '0.0.0.0', has error: 'connect ECONNREFUSED 0.0.0.0:5000'`

**Comment by birongliu** [comment]
And your password in application.yml should be same as the node configuration for erelajs

**Comment by JustANormalProgramm3r** [comment]
the passwords are the same

**Comment by birongliu** [comment]
And the port should be same as well so you have 5000 than both should be same

**Comment by Spiderjockey02** [comment]
ECONNREFUSED  means it couldn't connect to the port on the that IP, what is your host and you running them both on the same system?

**Comment by JustANormalProgramm3r** [comment]
the host is 0.0.0.0 and i'm running them both on the same system

**Comment by Spiderjockey02** [comment]
If you have discord it might be best to join our support server so we see screenshots etc easier? https://discord.gg/8g6zUQu

**Comment by JustANormalProgramm3r** [comment]
i'm ~comput3r~
