### ISSUE TITLE
queue command does not function.

### ISSUE THREAD

**Issue by Prothagarus** [Spiderjockey02/Discord-Bot#561]
**Describe the bug**
Queue command returns application did not respond instead of list of queued songs

**To Reproduce**
1. use /play to add two songs to the queue
2. use /queue command to list songs

**Expected behavior**
queue of songs displays

**Screenshots**
![image](https://github.com/Spiderjockey02/Discord-Bot/assets/14187325/d06b0e9b-e8dd-496b-8270-c3e93875987e)

**Device (please complete the following information):**
 - OS:Windows 10
 - Browser Discord?
 - Version latest branch

**Additional context**

**Comment by Spiderjockey02** [comment]
Any console errors when u run the command?

**Comment by Prothagarus** [comment]
![image](https://github.com/Spiderjockey02/Discord-Bot/assets/14187325/101f87aa-6052-4c9e-9c25-e2ac6edc398e)

**Comment by Spiderjockey02** [comment]
PR that fixed this has been merged to master.
