### ISSUE TITLE
Bot won't start.

### ISSUE THREAD

**Issue by AToska21** [Spiderjockey02/Discord-Bot#74]
I have been trying to start the bot, but it just keeps erroring at the KSoft API key. Is there anyway I can remove this restriction?

1. Open config.js
2. Remove the KSoft API key. 
3. Start the bot.
4. Bot shuts down.

**Expected behavior**

The bot is supposed to start and work as intended.

 - OS: Windows 10

**Comment by Spiderjockey02** [comment]
Go to src/scripts/verify-config.js and remove the Ksoft.api check and then restart your bot. 

If you have anymore problems just join the support server as I'm more active on discord.

**Comment by AToska21** [comment]
Thank you!
