### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by DJbeast2** [Spiderjockey02/Discord-Bot#76]
when starting up the bot with all api keys in config.js it shows this

(node:6356) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (C:\Users\Syvel\Desktop\Discord-Bot-master\node_modules\discord.js\src\sharding\Shard.js:163:16)      
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Spiderjockey02** [comment]
99% of the time this error is caused by a bad host. Try hosting on a different service if this error still occurs join the support discord server.
