### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by DJbeast2** [Spiderjockey02/Discord-Bot#77]
so I fixed the last problem i had now im having 2 more problems

ERROR Node: 'localhost', has error: 'connect ECONNREFUSED 127.0.0.1:2333'.

and 

ERROR Cannot find module '../helpers/DiscordBotListUpdate'

any help and ill give a star

**Comment by rayhan0614** [comment]
the first error is lavalink
if hosting on a server, you need to create and host a lavalink server, then go to src/base/Audio-Player.js and change the host name there, if you cant create one or dont know whats lavalink dm me on discord DirieSoftie#6666 ill help u out

the second error
ERROR Cannot find module '../helpers/DiscordBotListUpdate' can be ignored, its being worked on.
