### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by omi187** [Spiderjockey02/Discord-Bot#78]
[00:43:58]: LOG =-=-=-=-=-=-=- Config file Verification -=-=-=-=-=-=-= 
[00:43:58]: LOG Verifing config.. 
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open 'src/modules/logging/logs/roll-2021.01.10.log'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/modules/logging/logs/roll-2021.01.10.log'
}

when i try to run the bot

**Comment by Spiderjockey02** [comment]
just create the file in that directoy with the name it says. This is a rare bug out of my control sorry.
