### ISSUE TITLE
mongodb connect

### ISSUE THREAD

**Issue by jewelalex** [Spiderjockey02/Discord-Bot#96]
hello sir im trying to self host your bot but i dont know how to connect mongodb i have installed mongodb on my server ....

will you plz tell me how to do ....

thx 
best regards

**Comment by Spiderjockey02** [comment]
this is the link for mongoDB when running on the same server:
mongodb://localhost:27017/database

**Comment by jewelalex** [comment]
where have database i just have to put my db name m i right sir

**Comment by Spiderjockey02** [comment]
I'm sorry, I don't understand what you wrote.

**Comment by jewelalex** [comment]
one more think is that im haveing problem with all API is that all API are important cos  i dont have all API

**Comment by jewelalex** [comment]
mongodb://localhost:27017/(onr here my database name)

**Comment by Spiderjockey02** [comment]
> mongodb://localhost:27017/(onr here my database name)

yes that is correct.

**Comment by Spiderjockey02** [comment]
> one more think is that im haveing problem with all API is that all API are important cos i dont have all API

just fill out the ones you need and then remove the if statements of the ones you don't have in src/scripts/verify-config.js

**Comment by jewelalex** [comment]
ok sir i just want to use for music play and i think for rest like meme poll and reaction no need API

so for music play which API important 

thx

**Comment by Spiderjockey02** [comment]
> ok sir i just want to use for music play and i think for rest like meme poll and reaction no need API
> 
> so for music play which API important
> 
> thx

there is no API for music play, only for spotify

**Comment by jewelalex** [comment]
so may i remove all API to run Bot its will work with all comand?

**Comment by jewelalex** [comment]
hello sir
 i find this erroe
############

Error: Cannot find module './modules/logging/logger'
Require stack:
- /root/prottoy/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/prottoy/src/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/prottoy/src/index.js' ]
}

################
